spring.config.import=optional:file:env.properties
server.servlet.context-path=/helldivers/api/v1
spring.datasource.url=${SPRING_DATASOURCE_URL:${POSTGRES_DB_LOCAL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properpies.hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect
spring.jpa.properties.hibernate.format_sql=true
